name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        env: [dev, prod, staging]
        
    environment: ${{ matrix.env }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo key is ${{ secrets.key }}
