name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        env: [dev, prod, staging]
        
    environment: ${{ matrix.env }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Environments
        run: echo ${{ matrix.env }}
      
      - name: Upcase environment
        run: |
          echo "envUpper=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: use envUpper
        run: echo ${envUpper}

      - name: Compile
        run: echo key is ${{ secrets.key }}
        
      - name: Configure creds
        env:
          envUpper: ${envUpper}
        run: echo ${{ format('AWS_{0}_ACCESS_KEY_ID', env.envUpper) }}
