name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        env: [dev, prod, staging]
        
    environment: ${{ matrix.env }}
    
    steps:
      - uses: actions/checkout@v2
      
      - id: toUpperCase
        run: |
          export upperCaseValue = $(echo "console.log('${{ matrix.environment }}'.toUpperCase());" | node)
          echo ::set-output name=environment::$upperCaseValue

      - name: Compile
        run: echo key is ${{ secrets.key }}
        
      - name: Configure creds
        env:
          ENVIRONMENT: ${{ steps.toUpperCase.outputs.environment }}
        run: echo ${{ format('AWS_{0}_ACCESS_KEY_ID', env.ENVIRONMENT) }}
